name: Unit Tests

on:
  workflow_dispatch:
    inputs:
      clearCaches:
        description: "Clear workflow caches where possible"
        required: false
        type: string
  pull_request:
  push:
    # Ignore merge queue branches on push; avoids merge_group+push concurrency race since ref is same
    branches-ignore:
      - 'gh-readonly-queue/**'
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit:
    name: JUnit Tests (${{ matrix.name }})
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
        # macOS 14 is in beta and runs on Apple Silicon [M1]
        os: [ubuntu-latest, macos-14]
        # define 'name' so we don't need to update branch protection rules if the os changes
        include:
          - os: ubuntu-latest
            name: ubuntu
          - os: macos-14
            name: macos
    runs-on: ${{ matrix.os }}
    #env:
    #  CODACY_TOKEN: ${{ secrets.CODACY_TOKEN }}
    steps:
      - name: Configure Windows Pagefile
        uses: al-cheb/configure-pagefile-action@v1.4
        if: contains(matrix.os, 'windows')
        with:
          minimum-size: 8GB
          maximum-size: 12GB
          disk-root: "C:"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 50

      - name: Configure JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        timeout-minutes: 5
        with:
          # Only write to the cache for builds on the 'main' branches, stops branches evicting main cache
          # Builds on other branches will only read from main branch cache writes
          # Comment this and the with: above out for performance testing on a branch
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
          gradle-home-cache-cleanup: true
          # Windows runner currently having cache pollution issues, disable cache for the platform
          cache-disabled: ${{ contains(matrix.os, 'windows') }}
          build-scan-publish: true
          build-scan-terms-of-service-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-service-agree: "yes"

      - name: Upload Transforms directory before
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: transforms-androidjar-before-${{ matrix.os }}
          path: ~/.gradle/caches/transforms-4/f46cf63d0a549c8bc814e25133f449eb

      - name: Clear Caches Optionally
        if: "${{ github.event.inputs.clearCaches != '' }}"
        shell: bash
        run: |
          du -sk ~/.gradle
          rm -fr ~/.gradle
          du -sk ~/.gradle || echo ~/.gradle is gone

      - name: Gradle Dependency Download
        uses: nick-invision/retry@v3
        with:
          timeout_minutes: 10
          retry_wait_seconds: 60
          max_attempts: 3
          command: ./gradlew robolectricSdkDownload --daemon

      - name: Run Unit Tests
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: :AnkiDroid:testPlayDebugUnitTest --tests "com.ichi2.utils.MapUtilTest" jacocoUnitTestReport --daemon --info

      - name: Stop Gradle
        if: contains(matrix.os, 'windows')
        uses: gradle/gradle-build-action@v3
        with:
          arguments: --stop

      - uses: codecov/codecov-action@v3
        with:
          verbose: true

      - name: Upload Transforms directory after
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: transforms-androidjar-after-${{ matrix.os }}
          path: ~/.gradle/caches/transforms-4/f46cf63d0a549c8bc814e25133f449eb
